[package]
name = "hcnet-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_hcnet_core"
crate-type = ["staticlib"]

[dependencies]
log = "0.4.17"
cxx = "1.0"
im-rc = "15.0.0"
base64 = "0.13.0"
hcnet-contract-env-host = { git = "https://github.com/hcnet/rs-hcnet-contract-env", rev = "8e6c6a2", features = [
    "vm",
] }
